### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by Sarthak-Mittal** [Sarthak-Mittal/ifsc#1]
Add a new favicon icon signifying its a banking app. Something similar to 🏛️

**Comment by Apoorve73** [comment]
I would like to take up that!

**Comment by Apoorve73** [comment]
> I would like to take up that!

Where do I need to add that?

**Comment by Sarthak-Mittal** [comment]
> I would like to take up that!

You can proceed.

**Comment by Apoorve73** [comment]
Awesome!
