### ISSUE TITLE
Add topic `hacktoberfest`

### ISSUE THREAD

**Issue by ansidev** [Sarthak-Mittal/ifsc#11]
I created a pull request and checked Hacktoberfest Dashboard.

Problem:

Hacktoberfest is warning: **Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.**

Expected:

No warning anymore.

**Comment by Sarthak-Mittal** [comment]
I have added the required tags to the repository, check now. Let me know if you are still facing the issue.

**Comment by ansidev** [comment]
The problem was solved! Thanks!
