### ISSUE TITLE
Add icon for 'View on Google maps' feature

### ISSUE THREAD

**Issue by Sarthak-Mittal** [Sarthak-Mittal/ifsc#15]
It would we real convenient if there is an icon along with the link 'View on Google Maps'. A button here would be a plus point as per usability

![ifsc](https://user-images.githubusercontent.com/15452197/95587121-46260600-0a5f-11eb-830b-90109eae62e0.PNG)

**Comment by ArturBa** [comment]
I'm on it

**Comment by syauqy** [comment]
let me know what you think. Check this #18

**Comment by Sarthak-Mittal** [comment]
@ArturBa asked fixed, I think they are working on it already.

**Comment by ArturBa** [comment]
Sorry, for keeping you waiting. I'd some other things to do. Please check #20

**Comment by Sarthak-Mittal** [comment]
Thanks @ArturBa for your contributions!
