### ISSUE TITLE
Add content to 'About' page

### ISSUE THREAD

**Issue by Sarthak-Mittal** [Sarthak-Mittal/ifsc#16]
The about page of this app is empty. Need to put up content in there, you can refer to the Introduction and Description section of [Readme](https://github.com/Sarthak-Mittal/ifsc/blob/master/README.md) of this repository. You can also refer [wiki](https://en.wikipedia.org/wiki/Indian_Financial_System_Code) or any reliable resource to add a line or two.

Briefly cover the following, not necessarily with the following heading

- What this project is about?
- What is IFSC?
- Describe the Razorpay API used to fetch data, link their website and GitHub repo for reference.

**Make sure everything stays responsive**

Add content on this empty page
![about](https://user-images.githubusercontent.com/15452197/95589112-ec730b00-0a61-11eb-99ac-861b212e8e64.PNG)

**Comment by syauqy** [comment]
Can I work on this?

**Comment by Sarthak-Mittal** [comment]
Yes, please!

**Comment by masterdbpereira** [comment]
Working on it

**Comment by Sarthak-Mittal** [comment]
@masterdbpereira I think @syauqy is working on it already. Let them confirm, if not you can go ahead.

**Comment by mayankd147** [comment]
I want to work on this as well!

**Comment by masterdbpereira** [comment]
> @masterdbpereira I think @syauqy is working on it already. Let them confirm, if not you can go ahead.

If @syauqy already worked on this, just drop my pull request. It's my first action towards open-source.

**Comment by syauqy** [comment]
Hi, @Sarthak-Mittal please see #24 . Please let me know what you think

**Comment by Sarthak-Mittal** [comment]
> Hi, @Sarthak-Mittal please see #24 . Please let me know what you think

I have made some review comments, please address them.

**Comment by Sarthak-Mittal** [comment]
@syauqy thanks for your contributions!
