### ISSUE TITLE
Containerize the project

### ISSUE THREAD

**Issue by bishtsaurabh5** [Sarthak-Mittal/ifsc#22]
Idea:
I am thinking of containerizing this project.

Description:
Containerizing this project will help to run it without the need for any additional dependencies like angular, node etc.

Solution:
1) Dockerize the project
2) A custom build script to build and dockerize the latest project

**Comment by bishtsaurabh5** [comment]
Can I work on this issue If you find this as valid ?

**Comment by bishtsaurabh5** [comment]
Reopening this issue as I closed it by mistake.
Can I start working on this ?

**Comment by Sarthak-Mittal** [comment]
You can work on this. I was also thinking to automate deployment through Github Actions. If you want you can also look into that

**Comment by Sarthak-Mittal** [comment]
Merged #23 for this
