### ISSUE TITLE
Configure Github Actions script for Continuous Deployment

### ISSUE THREAD

**Issue by Sarthak-Mittal** [Sarthak-Mittal/ifsc#25]
Configure Github actions script for continuous deployment of the master branch. You can refer [Github Actions](https://github.com/features/actions)

Open for any other tool you know of for automated deployment on Github pages.

**Comment by bishtsaurabh5** [comment]
I can pick this up after Containerization commit

**Comment by Sarthak-Mittal** [comment]
I was trying my hand at this. Build keeps failing, need to fix that. I hope the below script might come in handy

---
name: Build and Deploy

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: actions/setup-node@v1 #this installs node and npm for us
      with:
        node-version: '12.x'
    - uses: actions/cache@v1 # this allows for re-using node_modules caching, making builds a bit faster.
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-    
    - name: Build
      run: |
        npm install
        npm run-script deploy
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: SHA256:qK2PuGso5dA95xjcEI6ZnX1caMeSm8gtJ1vHV31wpyk
        BRANCH: gh-pages
        FOLDER: dist/ifsc

**Comment by bishtsaurabh5** [comment]
Do you have logs ?
I was also trying to run with the following script and error , Can you help me I do not have much idea abiut node and angular 
####################################################################################################
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ workflows ]
  pull_request:
    branches: [ workflows ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g @angular/cli #install angular cli
    - run: npm link @angular/cli #link angular cli
    - run: npm install
    - run: ng build
    - run: ng test
########################################################################################



Run ng build
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'ansi-colors'
Require stack:
- /opt/hostedtoolcache/node/12.18.4/x64/lib/node_modules/@angular/cli/utilities/color.js
- /opt/hostedtoolcache/node/12.18.4/x64/lib/node_modules/@angular/cli/lib/init.js
- /opt/hostedtoolcache/node/12.18.4/x64/lib/node_modules/@angular/cli/bin/ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/opt/hostedtoolcache/node/12.18.4/x64/lib/node_modules/@angular/cli/utilities/color.js:11:20)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/hostedtoolcache/node/12.18.4/x64/lib/node_modules/@angular/cli/utilities/color.js',
    '/opt/hostedtoolcache/node/12.18.4/x64/lib/node_modules/@angular/cli/lib/init.js',
    '/opt/hostedtoolcache/node/12.18.4/x64/lib/node_modules/@angular/cli/bin/ng'
  ]
}
Error: Process completed with exit code 1.

**Comment by Sarthak-Mittal** [comment]
@bishtsaurabh5 Awesome work with #29 .
