### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by Sarthak-Mittal** [Sarthak-Mittal/ifsc#28]
Add a minimalistic and responsive footer

**Comment by Guiguerreiro39** [comment]
Hello,
Can I be assigned to this?

**Comment by Sarthak-Mittal** [comment]
Here you go!

**Comment by bhantsi** [comment]
I can do this

**Comment by rohanshenoy96** [comment]
Can I take it up? @Sarthak-Mittal

**Comment by Sarthak-Mittal** [comment]
@bhantsi @rohanshenoy96 you both are welcome!

**Comment by rohanshenoy96** [comment]
Hi @Sarthak-Mittal. It looks like animation is causing some issue with routing and footer. Would you like to keep it or removing it is okay?

**Comment by Sarthak-Mittal** [comment]
See if you can find any solution with animation on. If it is taking too much of time, disable animation for now. We can work on animation later.
