### ISSUE TITLE
[feat] message on wrong IFSC input

### ISSUE THREAD

**Issue by ayaankhan98** [Sarthak-Mittal/ifsc#3]
Display a message if no data found related to the entered IFSC code.

**Comment by shubhi23994** [comment]
I can take this up

**Comment by ayaankhan98** [comment]
sure go ahead @shubhi23994

**Comment by Sarthak-Mittal** [comment]
Hey! Before getting starting, let us discuss how you plan to proceed.
I have two ideas ATM:
 

- A custom validator for the IFSC code input field, maybe regex based. It would not spam the API in case of an invalid IFSC code.

- A styled yet decent "No data found" or "Invalid IFSC code" message in the case when invalid data is returned from API.

If you have some other suggestions, let's discuss it. @shubhi23994 @ayaankhan98

**Comment by ayaankhan98** [comment]
@Sarthak-Mittal i think a regex based validator will not give accurate results always, it will be good if @shubhi23994 goes with both approaches first check the given IFSC with regex if it's is valid according to regex then fetch the data from the API, at this point there are two possible cases we can have valid data in one case and invalid in other case, if data is invalid then simply put a decent message on screen.

**Comment by Sarthak-Mittal** [comment]
Yes, this sounds good @ayaankhan98 . @shubhi23994 you may proceed on these lines.

**Comment by Sarthak-Mittal** [comment]
@shubhi23994 do we have any update on this?

**Comment by shubhi23994** [comment]
@Sarthak-Mittal  I started working on this yesterday but since I have a linux system , I am facing issues with ng command. Getting any other environment can take some time.So won't be able to work on this before weekend. So if anyone else volunteer for this you can re-assign it.

**Comment by ayaankhan98** [comment]
> @Sarthak-Mittal I started working on this yesterday but since I have a linux system , I am facing issues with ng command. Getting any other environment can take some time.So won't be able to work on this before weekend. So if anyone else volunteer for this you can re-assign it.

@shubhi23994 
can you please mention what problem you are facing on linux?

**Comment by shubhi23994** [comment]
@Sarthak-Mittal  Initially I was getting ng commands issue but I think that was because of the node version. I have resolved the issue. Will update you on the progress soon. Sorry for the delayed response!

**Comment by Sarthak-Mittal** [comment]
Hey @shubhi23994 , I wanted to make sure if things were still in progress. Let me know what's the update on it.

**Comment by rohanshenoy96** [comment]
Hi @Sarthak-Mittal. I was also working on this. I'm attaching screenshots let me know if u need anything else in this
Error case
![image](https://user-images.githubusercontent.com/37835789/95678094-f757a800-0be7-11eb-9858-6c6c92636007.png)
Success case
![image](https://user-images.githubusercontent.com/37835789/95678099-fd4d8900-0be7-11eb-96bf-da21ed2d6c3d.png)

**Comment by Sarthak-Mittal** [comment]
Looks good to me!

**Comment by rohanshenoy96** [comment]
Created a pull request. Please verify and let me know if anything else is required @Sarthak-Mittal

**Comment by Sarthak-Mittal** [comment]
Thanks @rohanshenoy96 for your contributions. Merged #26 for this.
