### ISSUE TITLE
Style 'Search' and 'Clear' buttons

### ISSUE THREAD

**Issue by Sarthak-Mittal** [Sarthak-Mittal/ifsc#4]
- [ ] A clear distinction for both the buttons

- [ ] Keep a check on how they look when disabled

Keep the buttons decent. Make sure they follow the above two parameters at least.

**Comment by sahas-01** [comment]
Hey there, could you please elaborate on the second point?

**Comment by Sarthak-Mittal** [comment]
> Hey there, could you please elaborate on the second point?

Sorry, it's a bit confusing. All I mean is just keep then distinct even when they are disabled

**Comment by smatthies** [comment]
Would like to pick this up and added a pull request :)
