### ISSUE TITLE
Add icon (✅,❌) instead of boolean values

### ISSUE THREAD

**Issue by Sarthak-Mittal** [Sarthak-Mittal/ifsc#8]
API returns boolean values for UPI, NEFT, RTGS, and IMPS fields. Currently, those booleans are displayed. Need to show icons in place of true and false text. 

- Green colored check/tick icon (✅) when the returned value is `true` 

- Else show a red-colored cross icon (❌). 

You can refer [Font Awesome](https://fontawesome.com/) for icons.

**Comment by SaulEiros** [comment]
Hi! Can i give you a hand with this?

**Comment by Sarthak-Mittal** [comment]
Sure! Go ahead @SaulEiros

**Comment by Sarthak-Mittal** [comment]
Issue fixed with this [PR #10 ](https://github.com/Sarthak-Mittal/ifsc/pull/10) and [commit](https://github.com/Sarthak-Mittal/ifsc/commit/3dc9a4a205b417f5aaa57ec71ba2e522ae68ffbf)
