### ISSUE TITLE
Improve bootstrap layout for mobile view

### ISSUE THREAD

**Issue by Sarthak-Mittal** [Sarthak-Mittal/ifsc#9]
When API results are populated on the page. Currently, everything is stacked up in the mobile view. Need to improve the layout so everything looks clean and not stacked in the mobile view.

**Comment by sanskarsri** [comment]
i can help you out, tell me how you want it. It will look clean if in mobile view all the buttons are seperate on a new line!

**Comment by ansidev** [comment]
@Sarthak-Mittal Could you give the expected view on mobile? The requirement is not clear to me.

**Comment by Sarthak-Mittal** [comment]
@ansidev I have fixed basic layout for all viewports. It would be helpful if you can review and suggest how can we better improve it.
